name: hrk_flutter_batteries
version: 0.1.0

description: >-
  A library to accumulate required flutter helper and utility codes
repository: https://github.com/hrishikesh-kadam/hrk_flutter_batteries
topics:
  - batteries
  - flutter-batteries

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  hrk_analysis: ^0.2.0

flutter:
