name: playground_app
version: 1.0.0+1

description: >-
  Playground app which demonstrates hrk_flutter_batteries' Widgets, Helper, Utility codes.
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  hrk_batteries: ^2.1.0
  hrk_flutter_batteries: '>=0.1.0-pre.4 <1.0.0'
  hrk_logging: '>=0.2.0 <1.0.0'
  hrk_nasa_apis: ^1.0.0
  hrk_nasa_apis_test: ^1.0.0
  go_router: ^14.2.7
  json_annotation: ^4.9.0
  flutter_bloc: ^8.1.6
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.4
  freezed_annotation: ^2.4.4
  material_color_utilities: '>=0.11.1 <1.0.0'
  url_launcher: ^6.3.0
  recase: ^4.1.0
  pubspec_parse: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hrk_analysis: ^1.0.0
  hrk_flutter_test_batteries: ^1.1.0
  checks: '>=0.3.0 <1.0.0'
  mockito: ^5.4.4
  build_runner: ^2.4.12
  go_router_builder: ^2.7.1
  import_sorter:
    git:
      url: https://github.com/fluttercommunity/import_sorter.git
      ref: 641f363d40a4ffb42ab577a43433fc48c5059b19
  freezed: ^2.5.7
  json_serializable: ^6.8.0

dependency_overrides:
  hrk_flutter_batteries:
    path: '../'

flutter:
  uses-material-design: true
  generate: true
  assets:
    - pubspec.yaml
    - assets/app-icons/app-icon.png
    # - assets/fonts/Roboto/
    # - assets/fonts/MaterialIcons/

import_sorter:
  comments: false
  ignored_files:
    - '.*\.mocks\.dart'
    - test[/\\]src[/\\]config[/\\]hydrated_bloc\.dart
